# This is a basic workflow to help you get started with Actions

name: Purpleair trigger

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Runs "every 10 minutes" (see https://crontab.guru)
    - cron: '*/10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      
      - name: Get purpleair pm2.5
        run: |
          PM25=`curl -s https://api.purpleair.com/v1/sensors/${{ secrets.PURPLEAIR_SENSOR_ID }}?api_key=${{ secrets.PURPLEAIR_API_KEY }} | grep \ \"pm2.5\" | cut -d ':' -f2 | cut -d ',' -f1`
          echo "PM25 is $PM25!"
          if (( $(echo "$PM25 > 20" |bc -l) )); then
            echo "Starting the fan!"
            curl -X POST ${{ secrets.IFTTT_FANSTART_WEBHOOK_URL }}
          fi
          if (( $(echo "$PM25 < 5" |bc -l) )); then
            echo "Stopping the fan!"
            curl -X POST ${{ secrets.IFTTT_FANSTOP_WEBHOOK_URL }}
          fi

